### ISSUE TITLE
[compdat] Add support for * notation in WELOPEN

### ISSUE THREAD

**Issue by lindjoha** [equinor/ecl2df#314] opened 2021-06-02 08:21 UTC
I think the compdat export crashes when WELOPEN keyword contains * notation, f.ex like this:

```
WELOPEN
   'D_*'  'OPEN'  /
/
```

The Error message is also a bit confusing:

```
  File "/prog/res/komodo/2021.05.01-py36-rhel7/root/lib/python3.6/site-packages/ecl2df/compdat.py", line 399, in applywelopen
    "(I=%s,J=%s,K=%s)" % (row["I"], row["J"], row["K"])
ValueError: A WELOPEN keyword is not acting on any existing connection. (I=None,J=None,K=None)
```

**Comment by berland** [comment] 2021-06-02 08:46
Duplicate of #218 ?

**Comment by lindjoha** [comment] 2021-06-02 09:42
It is certainly related, but I don't know if it's exactly the same. I was not using WLIST when I got this error

**Comment by berland** [comment] 2021-06-02 09:49
No, it is not exactly the same.

**Comment by lindjoha** [comment] 2021-07-14 08:39
Solved in PR #333

**Closed** 2021-08-24 13:08 UTC
Labels: enhancement
