### ISSUE TITLE
merge vfp2csv into ecl2df

### ISSUE THREAD

**Issue by miroine** [equinor/ecl2df#114] opened 2020-03-19 09:47 UTC
as per today ... we don t have any parser for VLP's (vfp2csv has not been yet refactored to py3 ?) ... is it possible to parse that directly through ecl2df ? would it be available in the future ?

**Comment by berland** [comment] 2020-03-19 09:59
Duplicate of #7

**Closed by berland** 2020-03-19 09:59 UTC
Labels: duplicate, question
